version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: local_postgres
    restart: always
    environment:
      - POSTGRES_USER=EXAMPLE_USER
      - POSTGRES_PASSWORD=EXAMPLE_PASSWORD
      - POSTGRES_DB=EXAMPLE_DB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: